version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      run:
        name: trying to push to heroku
        command: |
          git push https://heroku:df2a271f-b601-4f67-9c41-cb4c72e06568@git.heroku.com/intense-anchorage-40867.git master
